task_references = dict(
    sst2=["Is the sentiment of this sentence positive or negative?",
          "Is the sentiment of this text positive or negative?",
          "Would you classify this sentence as having a positive or negative sentiment?",
          "Do you think this sentence has a positive or negative tone?",
          "Would you consider the sentiment of this sentence to be positive or negative?",
          "How would you rate the sentiment of this sentence: positive or negative?",
          "How would the sentiment of this sentence be described? Positive, Negative.",
          "Can you identify whether the sentiment of this sentence is positive or negative?",
          "What is the tone of this sentence: positive or negative?"],
    subj=["Is the subjectivity of this text objective or subjective?",
          "How would the subjectivity of this sentence be described? Objective, Subjective.",
          "Is this sentence objective or subjective in nature?",
          "In terms of subjectivity, is this sentence objective or subjective?",
          "How would you describe the subjectivity of this sentence: objective or subjective?",
          "Is the nature of this text's subjectivity objective or subjective?",
          "Classify the sentence based on its expression: objective, subjective",
          "Is this sentence factual or opinionated: objective, subjective",
          "Is this sentence based on facts or personal feelings: objective, subjective",
          "Determine if this sentence presents facts or opinions: objective, subjective"],
    agnews=["What is this text about? World, Sports, Business, Technology",
            "Which topic is this article about? World, Sports, Business, Technology",
            "What is the main topic discussed in this news story: World, Sports, Business, Technology",
            "What is the main topic discussed in this article: World, Sports, Business, Technology",
            "Which topic best captures the essence of this article? World, Sports, Business, Technology",
            "What is the most fitting summary for this article? World, Sports, Business, Technology",
            "Under which category does this article best fall? World, Sports, Business, Technology.",
            "Among World, Sports, Business, and Technology, which best captures the topic of this article?",
            "Classify this news report into the appropriate category: World, Sports, Business, Technology",
            "Which category best fits the topic of this article? World, Sports, Business, Technology",
            "To which category does this news article's topic belong: World, Sports, Business, Technology"],
    trec=["Is the question asking about an entity, a description, an abbreviation, an expression, a human, a location, or a number?",
          "Which one of the following options would the answer to this be?\nDescription, Entity, Abbreviation, Expression, Human, Location, Number",
          "What type of thing is the question asking about?\nDescription, Entity, Abbreviation, Expression, Human, Location, Number",
          "classify the answer of this question. is it an entity, a description, an abbreviation, an expression, a human, a location, or a number?",
          "What type is the answer to this question: entity, description, abbreviation, expression, human, location, or number?",
          "How would you classify the answer from the following options?\nDescription, Entity, Abbreviation, Expression, Human, Location, Number",
          "Choose the category that best fits the answer:\nDescription, Entity, Abbreviation, Expression, Human, Location, Number",
          "Is the question seeking information about an entity, a description, an abbreviation, an expression, a human, a location, or a number?",
          "Does the question pertain to an entity, a description, an abbreviation, an expression, a human, a location, or a number?"],
    sst5=["Is the sentiment of this sentence terrible, bad, neutral, good or great?",
          "Is the sentiment of this text terrible, bad, neutral, good or great?",
          "Would you classify this sentence as having a terrible, bad, neutral, good or great sentiment?",
          "Do you think this sentence has a terrible, bad, neutral, good or great tone?",
          "Would you consider the sentiment of this sentence to be terrible, bad, neutral, good or great?",
          "How would you rate the sentiment of this sentence: terrible, bad, neutral, good or great?",
          "How would the sentiment of this sentence be described? terrible, bad, neutral, good, great.",
          "Can you identify whether the sentiment of this sentence is terrible, bad, neutral, good or great?",
          "What is the tone of this sentence: terrible, bad, neutral, good or great?"]
)
